# This is a basic workflow to help you get started with Actions

name: Test and export

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: 
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DOCKER_ARGS:  '--rm  -v $(pwd):$(pwd) -w $(pwd)  -u $(id -u):$(id -g)'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  drc:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:8.0.2
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: run pcb-drc
        run:  kicad-cli pcb drc -exit-code-violations fmc-sfp.kicad_pcb
      - name: run sch-erc
        run:  kicad-cli sch drc -exit-code-violations fmc-sfp.kicad_sch
      # Runs a set of commands using the runners shell
      #- name: Run a command to make sure verilator is installed!
      
