# This is a basic workflow to help you get started with Actions

name: Test and export

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: 
      - '*'
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  PROJECT : 'fmc-sfp'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #Run_DRC:
  #  runs-on: ubuntu-latest
  #  container:
  #    image: kicad/kicad:8.0.2
  #    options: --user root 
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Run PCB DRC
  #      run: kicad-cli pcb drc --exit-code-violations --schematic-parity ${{env.PROJECT}}.kicad_pcb
  #    - name: Run Schematic  ERC
  #      run: kicad-cli sch erc --exit-code-violations  ${{env.PROJECT}}.kicad_sch
          
  Generate_Board_Files:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:8.0.2
      options: --user root 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: apt-get update && apt-get install zip git
      - run: git config --global --add safe.directory $(pwd)
      - name: Generate board files
        run: bash board_files.sh ${{env.PROJECT}}
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: ${{env.PROJECT}}-production
          path: manufacture/*
      
